### ISSUE TITLE
Does not detect keyboard

### ISSUE THREAD

**Issue by wapsi** [alexmohr/thinkpad-keyboard-backlight#9]
The program does not detect my Lenovo Thinkpad X270's integrated keyboard as a device which can turn the backlight back on after it has been turned off. All mice devices lights it up correctly.

In the help menu it says:
    -i ignore an input device
       This device does not re enable keyboard backlight.
       Separate multiple device by space.
       **Default: use all mice and keyboard.**

So I assume that it should use keyboard pressing as a trigger too, right?

**Comment by alexmohr** [comment]
That's correct could you post the output of `` ls /dev/input/by-path``please

**Comment by wapsi** [comment]
Here you go:
```
$ ls -l /dev/input/by-path/
total 0
lrwxrwxrwx 1 root root 10 Apr 29 17:52 pci-0000:00:14.0-usb-0:8:1.0-event -> ../event19
lrwxrwxrwx 1 root root  9 Apr 29 17:52 platform-pcspkr-event-spkr -> ../event8
lrwxrwxrwx 1 root root  9 Apr 29 18:06 platform-thinkpad_acpi-event -> ../event7
```
I'm guessing the internal keyboard is missing from there because according /proc/bus/input/devices the internal keyboard is event0 under /dev/input/
```
# cat /proc/bus/input/devices 
I: Bus=0011 Vendor=0001 Product=0001 Version=ab54
N: Name="AT Translated Set 2 keyboard"
P: Phys=isa0060/serio0/input0
S: Sysfs=/devices/platform/i8042/serio0/input/input0
U: Uniq=
H: Handlers=sysrq kbd leds event0 
B: PROP=0
B: EV=120013
B: KEY=402000000 3803078f800d001 feffffdfffefffff fffffffffffffffe
B: MSC=10
B: LED=7
```


I'm using openSUSE Leap 15.2 Beta, kernel: 5.3.18-lp152.11-default

**Comment by alexmohr** [comment]
That's the problem. I think it's a great idea to read the devices from   /proc/bus/input/devices I'll implement this in the next couple days

**Comment by wapsi** [comment]
Also one question (I don't think a separate issue is needed): If my keyboard backlight is off and I start the keyboard_backlight and then turn on the backlight manually after that (by hitting fn+space). Then the keyboard_backlight does not turn off the keyboard backlight after X seconds/idle timeout I've set. It only works if the keyboard light is turned on **before** starting the keyboard_backlight.

Is this intentional feature? I think the keyboard_backlight should always turn off the keyboard backlight if it's turned on after the idle timeout, right? (even if the user has changed the keyboard backlight status manually while keyboard_backlight is running)

**Comment by alexmohr** [comment]
That's another bug I'd say but an easy to fix one :)

**Comment by wapsi** [comment]
I'm trying to build the latest git version (dev branch) now but the compiled executable seg faults when I'm trying to start it:

```
localhost:~/x270/keyboard-backlight/build # export CC=/usr/bin/gcc-8
localhost:~/x270/keyboard-backlight/build # export CXX=/usr/bin/g++-8
localhost:~/x270/keyboard-backlight/build # cmake ../ && make
-- The C compiler identification is GNU 8.2.1
-- The CXX compiler identification is GNU 8.2.1
-- Check for working C compiler: /usr/bin/gcc-8
-- Check for working C compiler: /usr/bin/gcc-8 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-8
-- Check for working CXX compiler: /usr/bin/g++-8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /root/x270/keyboard-backlight/build
Scanning dependencies of target keyboard_backlight
[ 50%] Building CXX object CMakeFiles/keyboard_backlight.dir/kbd_backlight.cpp.o
/root/x270/keyboard-backlight/kbd_backlight.cpp: In function ‘void parse_opts(int, char* const*, std::vector<std::__cxx11::basic_string<char> >&, long unsigned int&, MOUSE_MODE&, std::__cxx11::string&, bool&, long int&)’:
/root/x270/keyboard-backlight/kbd_backlight.cpp:274:24: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
   if ((MOUSE_MODE::ALL > mode) | (MOUSE_MODE::NONE < mode)) {
        ~~~~~~~~~~~~~~~~^~~~~~
[100%] Linking CXX executable keyboard_backlight
[100%] Built target keyboard_backlight

localhost:~/x270/keyboard-backlight/build # ./keyboard_backlight 
Segmentation fault (core dumped)
```
I've set the environment variables to use gcc/g++ v8(.2.1) because if I use the openSUSE Leap 15.2 default gcc/g++ version (7.5.0) it does not recognize
`#include <filesystem>`
and if I try with
`#include <experimental/filesystem>`
the compilation fails even it finds the filesystem's headers.

Is there some possiblity to use debug build or something else to detect what exactly causes the seg fault here?

**Comment by alexmohr** [comment]
I wasn't able to build the project with gcc8 at all. I've added the necessary lib to enable building with gcc8 properly. I might be possible that this lead to segfault too. 

You can check out the lastest dev version and build it with ``cmake -DCMAKE_BUILD_TYPE=Debug ..`` to enable debug logs.

**Comment by wapsi** [comment]
Thanks, now the dev branch built OK and doesn't seg fault anymore. And now the keyboard backlight lights up even I change the status of the backlight manually (fn+space). And it detects now my keyboard correctly too!

The only misbehaviour I found now is that if I disable the backlight manually (fn+space) and after the idle timeout I move mouse / use keyboard the program lights up the backlight (even I was manually turned it off). So there's no possibility to turn off the backlight if the program is running (the program will turn it on always). Maybe /sys/class/leds/tpacpi::kbd_backlight/brightness_hw_changed can be use as a comparsion if the user has disabled the backlight manually? That file contains the information about last value user has set by using fn+space.

**Comment by alexmohr** [comment]
This only happened if you turn the lights off and afterwards do not move the mouse or press another key before the timeout is over. Should be fixed in the latest commit. Thanks for reporting it.

**Comment by wapsi** [comment]
Thank you very much! Now it's perfect (re-compiled your dev branch once again and everything works) :)

You can close this issue now if you want to.
